version: "3.8"

services:
  vote:
    container_name: vote
    build:
      dockerfile: vote/Dockerfile
    command: python app.py
    ports:
     - "5000:80"
    volumes:
     - votevolume:/var/data
    networks:
     - frontend
     - backend

  result:
    container_name: result
    build:
      dockerfile: result/Dockerfile
    command: nodemon server.js
    ports:
     - "5001:80"
    volumes:
     - resultvolume:/var/data
    networks:
     - frontend
     - backend

  worker:
    container_name: worker
    build:
      dockerfile: worker/Dockerfile
    networks:
     - backend

  redis:
    container_name: redis
    image: redis
    networks:
     - backend

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgressql/data

volumes:
  votevolume:
  resultvolume:
  pgdata:

networks:
  frontend:
  backend: